apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - image: wordpress:php8.1-apache
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: m-db-cluster-instance-1.ct5ersz6fo73.ap-northeast-2.rds.amazonaws.com
            - name: WORDPRESS_DB_PASSWORD
              value: 49096041aA
            - name: WORDPRESS_DB_USER
              value: admin
            - name: WORDPRESS_DB_NAME
              value: wordpress
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          nfs:
            path: /var/www/html
            server: fs-0a8ee6d4021e2c2a6.efs.ap-northeast-2.amazonaws.com
